// Add zero in front of numbers < 10
export function zeroPad(i) {
  if (i < 10) {
    i = "0" + i;
  }
  return i;
}

/* Required to set date */
export const Day = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export const monthsSmall = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/* Swami Vivekananda, Quotes:   https://en.wikiquote.org/wiki/Swami_Vivekananda  */  
export var quotes = [
{"1": "Arise, awake and Stop not till the Goal is Reached."},
{"2": "You cannot believe in God until you believe in yourself."},
{"3": "All truth is eternal."},
{"4": "Truth is nobody’s property; no race, no individual can lay any exclusive claim to it."},
{"5": "Truth is the nature of all souls."},
{"6": "“Comfort” is no test of truth; on the contrary, truth is often far from being “comfortable.”"},
{"7": "The unselfish man says, \"I will be last, I do not care to go to heaven\""},
{"8": "If there is sin, this is the only sin — to say that you are weak, or others are weak."},
{"9": "Where can we go to find God if we cannot see Him in our own hearts and in every living being?"},
{"10": "All the powers in the universe are already ours."},
{"11": "It is we who have put our hands before our eyes and cry that it is dark."},
{"12": "If you see something evil, think that you are not understanding it in the right light."},
{"13": "Nirvana is the realization of the Self"},
{"14": "All knowledge that the world has ever received comes from the mind."},
{"15": "The infinite library of the universe is in our own mind."},
{"16": "He who thinks, \"I will get Mukti before others\" is the selfish man"},
{"17": "“Face the brutes.” That is a lesson for all life — face the terrible, face it boldly."},
{"18": "All that is real in me is God; all that is real in God is I. "},
{"19": "By knowing God, we find that the kingdom of heaven is within us."},
{"20": "External nature is only internal nature writ large."},
{"21": "Go on saying, “I am free.” "},
{"22": "That man has reached immortality who is disturbed by nothing material."},
{"23": "I, for one, thoroughly believe that no power in the universe can withhold from anyone anything he really deserves."},
{"24": "He who thinks, \"I will possess everything\" is the selfish man"},
{"25": "He who thinks, \"I will get to heaven before others\" is the selfish man"},
{"26": "Truth can be stated in a thousand different ways, yet each one can be true."},
{"27": "Are great things ever done smoothly? Time, patience, and indomitable will must show."},
{"28": "Be a hero. Always say, “I have no fear.” Tell this to everyone—“Have no fear.”"},
{"29": "Desire, ignorance, and inequality—this is the trinity of bondage."},
{"30": "Despondency is not religion, whatever else it may be."},
{"31": "Do not look back upon what has been done. Go ahead!"},
{"32": "Every step I take in light is mine forever."},
{"33": "Everything must be sacrificed, if necessary, for that one sentiment: universality."},
{"34": "First, believe in the world—that there is meaning behind everything."},
{"35": "If superstition enters, the brain is gone."},
{"36": "Let us not depend upon the world for pleasure."},
{"37": "One who leans on others cannot serve the God of Truth."},
{"38": "Please everyone without becoming a hypocrite or a coward."},
{"39": "Superstition is our great enemy, but bigotry is worse."},
{"40": "The first sign that you are becoming religious is that you are becoming cheerful."},
{"41": "The greatest religion is to be true to your own nature. Have faith in yourselves!"},
{"42": "The idea of perfect womanhood is perfect independence."},
{"43": "If money help a man to do good to others, it is of some value else a mass of evil,"},
{"44": "There is no other teacher but your own soul."},
{"45": "You have to grow from the inside out. None can teach you, none can make you spiritual."},
{"46": "The will is not free—it is a phenomenon bound by cause and effect."},
{"47": "Feel like Christ and you will be a Christ; feel like Buddha and you will be a Buddha"},
{"48": "Condemn none: if you can stretch out a helping hand, do so."},
{"49": "Education is the manifestation of perfection present already in man. "},
{"50": "The mistake is that we cling to the body when it is the spirit that is really immortal."},
{"51": "The mind is but the subtle part of the body. You must retain great strength in your mind and words."},
{"52": "The past was great no doubt, but I sincerely believe that the future will be more glorious still."},
{"53": "The power of purity—it is a definite power."},
{"54": "He who thinks, \"I will have more money than others\" is the selfish man"},
{"55": "The whole universe is one. There is only one Self in the universe, only One Existence."},
{"56": "Only the moment you reject all help are you free."},
{"57": "Never fear what will become of you, depend on no one"},
{"58": "The whole secret of existence is to have no fear. "},
{"59": "The world is ready to give up its secrets if we only know how to knock."},
{"60": "There cannot be friendship without equality."},
{"61": "There is only one sin. That is weakness.... "},
{"62": "The only saint is that soul that never weakens, faces everything, and determines to die game."},
{"63": "This earth is higher than all the heavens; this is the greatest school in the universe."},
{"64": "This is no world. It is God Himself. In delusion we call it world."},
{"65": "To believe blindly is to degenerate the human soul. "},
{"66": "Be an atheist if you want, but do not believe in anything unquestioningly."},
{"67": "We are suffering from our own karma. It is not the fault of God. "},
{"68": "What we do is our own fault, nothing else. Why should God be blamed?"},
{"69": "We reap what we sow. We are the makers of our own fate. None else has the blame, none has the praise."},
{"70": "We want to know in order to make ourselves free. That is our life: one universal cry for freedom."},
{"71": "Whenever we attain a higher vision, the lower vision disappears of itself."},
{"72": "Who makes us ignorant? We ourselves. We put our hands over our eyes and weep that it is dark."},
{"73": "Woman has suffered for eons, and that has given her infinite patience and infinite perseverance."},
{"74": "Work and worship are necessary to take away the veil, to lift off the bondage and illusion."},
{"75": "Work on with the intrepidity of a lion but at the same time with the tenderness of a flower."},
{"76": "Worship of society and popular opinion is idolatry. The soul has no sex, no country, no place, no time."},
{"77": "It is our own mental attitude which makes the world what it is for us"},
{"78": "Our thought make things beautiful, our thoughts make things ugly."},
{"79": "The whole world is in our own minds. "},
{"80": "Take up an idea, devote yourself to it, struggle on in patience, and the sun will rise for you."},
{"81": "We must overcome difficulty by constant practice."},
{"82": "We must learn that nothing can happen to us unless we make ourselves susceptible to it."},
{"83": "All the strength and success you want is within ourselves."},
{"84": "Never mind failures; they are quite natural, they are the beauty of life, these failures."},
{"85": "Never mind the struggles, the mistakes"},
{"86": "..if you fail a thousand times, make the attempt once more."},
{"87": "Let positive, strong, helpful thoughts enter into your brains from very childhood. "},
{"88": "Let me tell you again that you must be pure and help any one who comes to you."},
{"89": "If there is dirt and dust on a mirror, we cannot see our image."},
{"90": "Ignorance and wickedness are the dirt and dust that are on the mirror of our hearts."},
{"91": "Selfishness is the chief sin, thinking of ourselves first."},
{"92": "He who thinks, \"I will eat first\" is the selfish man"},
{"93": "The Soul is not composed of any materials. It is unity indivisible. Therefore it must be indestructible."},
{"94": "Never mind if the delusion comes and says, “I am bound.” Dehypnotize the whole thing."},
{"95": "In one word, this ideal is that you are divine."},
{"96": "A few heart-whole, sincere, and energetic men and women can do more in a year than a mob in a century."},
{"97": "Never think there is anything impossible for the soul."},
{"98": "The unselfish man says, \"I will even go to hell if by doing so I can help my brothers.\" "},
{"99": "This unselfishness is the test of religion."},
{"100": "He who has more of this unselfishness is more spiritual."},
{"101": "This is the gist of all worship — to be pure and to do good to others."},
{"102": "People think they can do anything, and then they can go to a holy place, and their sins will be forgiven."},
{"103": "If a man goes with an impure mind into a temple, he adds to the sins that he had already."},
{"104": "If a man goes with an impure mind into a temple, goes home a worse man than when he left it."},
{"105": "Truth is the nature of all souls."},
{"106": "“Comfort” is no test of truth; on the contrary, truth is often far from being “comfortable.”"},
{"107": "The unselfish man says, \"I will be last, I do not care to go to heaven\""},
{"108": "If there is sin, this is the only sin — to say that you are weak, or others are weak."},
{"109": "Where can we go to find God if we cannot see Him in our own hearts and in every living being?"},
{"110": "All the powers in the universe are already ours."},
{"111": "It is we who have put our hands before our eyes and cry that it is dark."},
{"112": "If you see something evil, think that you are not understanding it in the right light."},
{"113": "Nirvana is the realization of the Self"},
{"114": "All knowledge that the world has ever received comes from the mind."},
{"115": "The infinite library of the universe is in our own mind."},
{"116": "He who thinks, \"I will get Mukti before others\" is the selfish man"},
{"117": "“Face the brutes.” That is a lesson for all life — face the terrible, face it boldly."},
{"118": "All that is real in me is God; all that is real in God is I. "},
{"119": "By knowing God, we find that the kingdom of heaven is within us."},
{"120": "External nature is only internal nature writ large."},
{"121": "Go on saying, “I am free.” "},
{"122": "That man has reached immortality who is disturbed by nothing material."},
{"123": "I, for one, thoroughly believe that no power in the universe can withhold from anyone anything he really deserves."},
{"124": "He who thinks, \"I will possess everything\" is the selfish man"},
{"125": "He who thinks, \"I will get to heaven before others\" is the selfish man"},
{"126": "Truth can be stated in a thousand different ways, yet each one can be true."},
{"127": "Are great things ever done smoothly? Time, patience, and indomitable will must show."},
{"128": "Be a hero. Always say, “I have no fear.” Tell this to everyone—“Have no fear.”"},
{"129": "Desire, ignorance, and inequality—this is the trinity of bondage."},
{"130": "Despondency is not religion, whatever else it may be."},
{"131": "Do not look back upon what has been done. Go ahead!"},
{"132": "Every step I take in light is mine forever."},
{"133": "Everything must be sacrificed, if necessary, for that one sentiment: universality."},
{"134": "First, believe in the world—that there is meaning behind everything."},
{"135": "If superstition enters, the brain is gone."},
{"136": "Let us not depend upon the world for pleasure."},
{"137": "One who leans on others cannot serve the God of Truth."},
{"138": "Please everyone without becoming a hypocrite or a coward."},
{"139": "Superstition is our great enemy, but bigotry is worse."},
{"140": "The first sign that you are becoming religious is that you are becoming cheerful."},
{"141": "The greatest religion is to be true to your own nature. Have faith in yourselves!"},
{"142": "The idea of perfect womanhood is perfect independence."},
{"143": "If money help a man to do good to others, it is of some value else a mass of evil,"},
{"144": "There is no other teacher but your own soul."},
{"145": "You have to grow from the inside out. None can teach you, none can make you spiritual."},
{"146": "The will is not free—it is a phenomenon bound by cause and effect."},
{"147": "Feel like Christ and you will be a Christ; feel like Buddha and you will be a Buddha"},
{"148": "Condemn none: if you can stretch out a helping hand, do so."},
{"149": "Education is the manifestation of perfection present already in man. "},
{"150": "The mistake is that we cling to the body when it is the spirit that is really immortal."},
{"151": "The mind is but the subtle part of the body. You must retain great strength in your mind and words."},
{"152": "The past was great no doubt, but I sincerely believe that the future will be more glorious still."},
{"153": "The power of purity—it is a definite power."},
{"154": "He who thinks, \"I will have more money than others\" is the selfish man"},
{"155": "The whole universe is one. There is only one Self in the universe, only One Existence."},
{"156": "Only the moment you reject all help are you free."},
{"157": "Never fear what will become of you, depend on no one"},
{"158": "The whole secret of existence is to have no fear. "},
{"159": "The world is ready to give up its secrets if we only know how to knock."},
{"160": "There cannot be friendship without equality."},
{"161": "There is only one sin. That is weakness.... "},
{"162": "The only saint is that soul that never weakens, faces everything, and determines to die game."},
{"163": "This earth is higher than all the heavens; this is the greatest school in the universe."},
{"164": "This is no world. It is God Himself. In delusion we call it world."},
{"165": "To believe blindly is to degenerate the human soul. "},
{"166": "Be an atheist if you want, but do not believe in anything unquestioningly."},
{"167": "We are suffering from our own karma. It is not the fault of God. "},
{"168": "What we do is our own fault, nothing else. Why should God be blamed?"},
{"169": "We reap what we sow. We are the makers of our own fate. None else has the blame, none has the praise."},
{"170": "We want to know in order to make ourselves free. That is our life: one universal cry for freedom."},
{"171": "Whenever we attain a higher vision, the lower vision disappears of itself."},
{"172": "Who makes us ignorant? We ourselves. We put our hands over our eyes and weep that it is dark."},
{"173": "Woman has suffered for eons, and that has given her infinite patience and infinite perseverance."},
{"174": "Work and worship are necessary to take away the veil, to lift off the bondage and illusion."},
{"175": "Work on with the intrepidity of a lion but at the same time with the tenderness of a flower."},
{"176": "Worship of society and popular opinion is idolatry. The soul has no sex, no country, no place, no time."},
{"177": "It is our own mental attitude which makes the world what it is for us"},
{"178": "Our thought make things beautiful, our thoughts make things ugly."},
{"179": "The whole world is in our own minds. "},
{"180": "Take up an idea, devote yourself to it, struggle on in patience, and the sun will rise for you."},
{"181": "We must overcome difficulty by constant practice."},
{"182": "We must learn that nothing can happen to us unless we make ourselves susceptible to it."},
{"183": "All the strength and success you want is within ourselves."},
{"184": "Never mind failures; they are quite natural, they are the beauty of life, these failures."},
{"185": "Never mind the struggles, the mistakes"},
{"186": "..if you fail a thousand times, make the attempt once more."},
{"187": "Let positive, strong, helpful thoughts enter into your brains from very childhood. "},
{"188": "Let me tell you again that you must be pure and help any one who comes to you."},
{"189": "If there is dirt and dust on a mirror, we cannot see our image."},
{"190": "Ignorance and wickedness are the dirt and dust that are on the mirror of our hearts."},
{"191": "Selfishness is the chief sin, thinking of ourselves first."},
{"192": "He who thinks, \"I will eat first\" is the selfish man"},
{"193": "The Soul is not composed of any materials. It is unity indivisible. Therefore it must be indestructible."},
{"194": "Never mind if the delusion comes and says, “I am bound.” Dehypnotize the whole thing."},
{"195": "In one word, this ideal is that you are divine."},
{"196": "A few heart-whole, sincere, and energetic men and women can do more in a year than a mob in a century."},
{"197": "Never think there is anything impossible for the soul."},
{"198": "The unselfish man says, \"I will even go to hell if by doing so I can help my brothers.\" "},
{"199": "This unselfishness is the test of religion."},
{"200": "He who has more of this unselfishness is more spiritual."},
{"201": "This is the gist of all worship — to be pure and to do good to others."},
{"202": "People think they can do anything, and then they can go to a holy place, and their sins will be forgiven."},
{"203": "If a man goes with an impure mind into a temple, he adds to the sins that he had already."},
{"204": "If a man goes with an impure mind into a temple, goes home a worse man than when he left it."},
{"205": "Truth is the nature of all souls."},
{"206": "“Comfort” is no test of truth; on the contrary, truth is often far from being “comfortable.”"},
{"207": "The unselfish man says, \"I will be last, I do not care to go to heaven\""},
{"208": "If there is sin, this is the only sin — to say that you are weak, or others are weak."},
{"209": "Where can we go to find God if we cannot see Him in our own hearts and in every living being?"},
{"210": "All the powers in the universe are already ours."},
{"211": "It is we who have put our hands before our eyes and cry that it is dark."},
{"212": "If you see something evil, think that you are not understanding it in the right light."},
{"213": "Nirvana is the realization of the Self"},
{"214": "All knowledge that the world has ever received comes from the mind."},
{"215": "The infinite library of the universe is in our own mind."},
{"216": "He who thinks, \"I will get Mukti before others\" is the selfish man"},
{"217": "“Face the brutes.” That is a lesson for all life — face the terrible, face it boldly."},
{"218": "All that is real in me is God; all that is real in God is I. "},
{"219": "By knowing God, we find that the kingdom of heaven is within us."},
{"220": "External nature is only internal nature writ large."},
{"221": "Go on saying, “I am free.” "},
{"222": "That man has reached immortality who is disturbed by nothing material."},
{"223": "I, for one, thoroughly believe that no power in the universe can withhold from anyone anything he really deserves."},
{"224": "He who thinks, \"I will possess everything\" is the selfish man"},
{"225": "He who thinks, \"I will get to heaven before others\" is the selfish man"},
{"226": "Truth can be stated in a thousand different ways, yet each one can be true."},
{"227": "Are great things ever done smoothly? Time, patience, and indomitable will must show."},
{"228": "Be a hero. Always say, “I have no fear.” Tell this to everyone—“Have no fear.”"},
{"229": "Desire, ignorance, and inequality—this is the trinity of bondage."},
{"230": "Despondency is not religion, whatever else it may be."},
{"231": "Do not look back upon what has been done. Go ahead!"},
{"232": "Every step I take in light is mine forever."},
{"233": "Everything must be sacrificed, if necessary, for that one sentiment: universality."},
{"234": "First, believe in the world—that there is meaning behind everything."},
{"235": "If superstition enters, the brain is gone."},
{"236": "Let us not depend upon the world for pleasure."},
{"237": "One who leans on others cannot serve the God of Truth."},
{"238": "Please everyone without becoming a hypocrite or a coward."},
{"239": "Superstition is our great enemy, but bigotry is worse."},
{"240": "The first sign that you are becoming religious is that you are becoming cheerful."},
{"241": "The greatest religion is to be true to your own nature. Have faith in yourselves!"},
{"242": "The idea of perfect womanhood is perfect independence."},
{"243": "If money help a man to do good to others, it is of some value else a mass of evil,"},
{"244": "There is no other teacher but your own soul."},
{"245": "You have to grow from the inside out. None can teach you, none can make you spiritual."},
{"246": "The will is not free—it is a phenomenon bound by cause and effect."},
{"247": "Feel like Christ and you will be a Christ; feel like Buddha and you will be a Buddha"},
{"248": "Condemn none: if you can stretch out a helping hand, do so."},
{"249": "Education is the manifestation of perfection present already in man. "},
{"250": "The mistake is that we cling to the body when it is the spirit that is really immortal."},
{"251": "The mind is but the subtle part of the body. You must retain great strength in your mind and words."},
{"252": "The past was great no doubt, but I sincerely believe that the future will be more glorious still."},
{"253": "The power of purity—it is a definite power."},
{"254": "He who thinks, \"I will have more money than others\" is the selfish man"},
{"255": "The whole universe is one. There is only one Self in the universe, only One Existence."},
{"256": "Only the moment you reject all help are you free."},
{"257": "Never fear what will become of you, depend on no one"},
{"258": "The whole secret of existence is to have no fear. "},
{"259": "The world is ready to give up its secrets if we only know how to knock."},
{"260": "There cannot be friendship without equality."},
{"261": "There is only one sin. That is weakness.... "},
{"262": "The only saint is that soul that never weakens, faces everything, and determines to die game."},
{"263": "This earth is higher than all the heavens; this is the greatest school in the universe."},
{"264": "This is no world. It is God Himself. In delusion we call it world."},
{"265": "To believe blindly is to degenerate the human soul. "},
{"266": "Be an atheist if you want, but do not believe in anything unquestioningly."},
{"267": "We are suffering from our own karma. It is not the fault of God. "},
{"268": "What we do is our own fault, nothing else. Why should God be blamed?"},
{"269": "We reap what we sow. We are the makers of our own fate. None else has the blame, none has the praise."},
{"270": "We want to know in order to make ourselves free. That is our life: one universal cry for freedom."},
{"271": "Whenever we attain a higher vision, the lower vision disappears of itself."},
{"272": "Who makes us ignorant? We ourselves. We put our hands over our eyes and weep that it is dark."},
{"273": "Woman has suffered for eons, and that has given her infinite patience and infinite perseverance."},
{"274": "Work and worship are necessary to take away the veil, to lift off the bondage and illusion."},
{"275": "Work on with the intrepidity of a lion but at the same time with the tenderness of a flower."},
{"276": "Worship of society and popular opinion is idolatry. The soul has no sex, no country, no place, no time."},
{"277": "It is our own mental attitude which makes the world what it is for us"},
{"278": "Our thought make things beautiful, our thoughts make things ugly."},
{"279": "The whole world is in our own minds. "},
{"280": "Take up an idea, devote yourself to it, struggle on in patience, and the sun will rise for you."},
{"281": "We must overcome difficulty by constant practice."},
{"282": "We must learn that nothing can happen to us unless we make ourselves susceptible to it."},
{"283": "All the strength and success you want is within ourselves."},
{"284": "Never mind failures; they are quite natural, they are the beauty of life, these failures."},
{"285": "Never mind the struggles, the mistakes"},
{"286": "..if you fail a thousand times, make the attempt once more."},
{"287": "Let positive, strong, helpful thoughts enter into your brains from very childhood. "},
{"288": "Let me tell you again that you must be pure and help any one who comes to you."},
{"289": "If there is dirt and dust on a mirror, we cannot see our image."},
{"290": "Ignorance and wickedness are the dirt and dust that are on the mirror of our hearts."},
{"291": "Selfishness is the chief sin, thinking of ourselves first."},
{"292": "He who thinks, \"I will eat first\" is the selfish man"},
{"293": "The Soul is not composed of any materials. It is unity indivisible. Therefore it must be indestructible."},
{"294": "Never mind if the delusion comes and says, “I am bound.” Dehypnotize the whole thing."},
{"295": "In one word, this ideal is that you are divine."},
{"296": "A few heart-whole, sincere, and energetic men and women can do more in a year than a mob in a century."},
{"297": "Never think there is anything impossible for the soul."},
{"298": "The unselfish man says, \"I will even go to hell if by doing so I can help my brothers.\" "},
{"299": "This unselfishness is the test of religion."},
{"300": "He who has more of this unselfishness is more spiritual."},
{"301": "This is the gist of all worship — to be pure and to do good to others."},
{"302": "People think they can do anything, and then they can go to a holy place, and their sins will be forgiven."},
{"303": "If a man goes with an impure mind into a temple, he adds to the sins that he had already."},
{"304": "If a man goes with an impure mind into a temple, goes home a worse man than when he left it."},
{"305": "Truth is the nature of all souls."},
{"306": "“Comfort” is no test of truth; on the contrary, truth is often far from being “comfortable.”"},
{"307": "The unselfish man says, \"I will be last, I do not care to go to heaven\""},
{"308": "If there is sin, this is the only sin — to say that you are weak, or others are weak."},
{"309": "Where can we go to find God if we cannot see Him in our own hearts and in every living being?"},
{"310": "All the powers in the universe are already ours."},
{"311": "It is we who have put our hands before our eyes and cry that it is dark."},
{"312": "If you see something evil, think that you are not understanding it in the right light."},
{"313": "Nirvana is the realization of the Self"},
{"314": "All knowledge that the world has ever received comes from the mind."},
{"315": "The infinite library of the universe is in our own mind."},
{"316": "He who thinks, \"I will get Mukti before others\" is the selfish man"},
{"317": "“Face the brutes.” That is a lesson for all life — face the terrible, face it boldly."},
{"318": "All that is real in me is God; all that is real in God is I. "},
{"319": "By knowing God, we find that the kingdom of heaven is within us."},
{"320": "External nature is only internal nature writ large."},
{"321": "Go on saying, “I am free.” "},
{"322": "That man has reached immortality who is disturbed by nothing material."},
{"323": "I, for one, thoroughly believe that no power in the universe can withhold from anyone anything he really deserves."},
{"324": "He who thinks, \"I will possess everything\" is the selfish man"},
{"325": "He who thinks, \"I will get to heaven before others\" is the selfish man"},
{"326": "Truth can be stated in a thousand different ways, yet each one can be true."},
{"327": "Are great things ever done smoothly? Time, patience, and indomitable will must show."},
{"328": "Be a hero. Always say, “I have no fear.” Tell this to everyone—“Have no fear.”"},
{"329": "Desire, ignorance, and inequality—this is the trinity of bondage."},
{"330": "Despondency is not religion, whatever else it may be."},
{"331": "Do not look back upon what has been done. Go ahead!"},
{"332": "Every step I take in light is mine forever."},
{"333": "Everything must be sacrificed, if necessary, for that one sentiment: universality."},
{"334": "First, believe in the world—that there is meaning behind everything."},
{"335": "If superstition enters, the brain is gone."},
{"336": "Let us not depend upon the world for pleasure."},
{"337": "One who leans on others cannot serve the God of Truth."},
{"338": "Please everyone without becoming a hypocrite or a coward."},
{"339": "Superstition is our great enemy, but bigotry is worse."},
{"340": "The first sign that you are becoming religious is that you are becoming cheerful."},
{"341": "The greatest religion is to be true to your own nature. Have faith in yourselves!"},
{"342": "The idea of perfect womanhood is perfect independence."},
{"343": "If money help a man to do good to others, it is of some value else a mass of evil,"},
{"344": "There is no other teacher but your own soul."},
{"345": "You have to grow from the inside out. None can teach you, none can make you spiritual."},
{"346": "The will is not free—it is a phenomenon bound by cause and effect."},
{"347": "Feel like Christ and you will be a Christ; feel like Buddha and you will be a Buddha"},
{"348": "Condemn none: if you can stretch out a helping hand, do so."},
{"349": "Education is the manifestation of perfection present already in man. "},
{"350": "The mistake is that we cling to the body when it is the spirit that is really immortal."},
{"351": "The mind is but the subtle part of the body. You must retain great strength in your mind and words."},
{"352": "The past was great no doubt, but I sincerely believe that the future will be more glorious still."},
{"353": "The power of purity—it is a definite power."},
{"354": "He who thinks, \"I will have more money than others\" is the selfish man"},
{"355": "Arise, awake and Stop not till the Goal is Reached."},
{"356": "You cannot believe in God until you believe in yourself."},
{"357": "All truth is eternal."},
{"358": "Truth is nobody’s property; no race, no individual can lay any exclusive claim to it."},
{"359": "Truth is the nature of all souls."},
{"360": "“Comfort” is no test of truth; on the contrary, truth is often far from being “comfortable.”"},
{"361": "The unselfish man says, \"I will be last, I do not care to go to heaven\""},
{"362": "If there is sin, this is the only sin — to say that you are weak, or others are weak."},
{"363": "Where can we go to find God if we cannot see Him in our own hearts and in every living being?"},
{"364": "All the powers in the universe are already ours."},
{"365": "It is we who have put our hands before our eyes and cry that it is dark."},
{"366": "If you see something evil, think that you are not understanding it in the right light."},
  // Default quote if something goes wrong during app processing - see app/index.js
{"367": "Arise, awake and Stop not till the Goal is Reached."}
];

